# imagenetS50 config

# Finetune from:
finetune: '~/mae_checkpoint/grid_multi.pth' # Change me

# Input tasks
in_domains: rgb

# Architecture
model: multivit_base
patch_size: 16
num_global_tokens: 1
drop_path_encoder: 0.1
output_adapter: convnext
decoder_dim: 6144
decoder_preds_per_patch: 16
decoder_depth: 4

# Train
epochs: 32
opt: adamw
lr: 0.0001 # = 1e-4
warmup_lr: 0.000001 # = 1e-6
min_lr: 1e-6
warmup_epochs: 5
batch_size: 16
input_size: 224
layer_decay: 0.75

# Augmentation
aug_name: simple

# Data
data_path: '/data/imagenet-S/ImageNetS50/semseg/train' # Change me
eval_data_path: '/data/imagenet-S/ImageNetS50/semseg/val' # Change me
num_classes: 256
dataset_name: imagenetS50
dist_eval: True
seg_reduce_zero_label: True
eval_freq: 1

# Misc.
find_unused_params: False

# Wandb and logging
log_wandb: False # Set to True to activate logging to Weights & Biases
wandb_project: 'multimae-finetune-semseg'
wandb_entity: null # Change if needed
wandb_run_name: ft_ade_64e_mae-b_rgb
log_images_wandb: True
log_images_freq: 5
output_dir: 'output/fintune/semseg/imagenetS50/grid' # Change if needed
